#!/bin/bash

#
# Update-Script for https://bots.discord.pw
#


# cd into bot-directory
cd $pwd;

# grab guild-count from stats.json
data=$(cat stats.json | jq -r '.guildCount');

# change data to valid json
data="{\"server_count\":"$data"}";

# for debugging
#echo $data;

# send the request as post
#
# replace <token> and <bot-id> to make it work for your own bot!
#
curl \
  -X POST \
  -H "Authorization: <token>" \
  -H "Content-Type: application/json" \
  -d $data \
  https://bots.discord.pw/api/bots/<bot-id>/stats;
